### ISSUE TITLE
Ability to highlight all parent directories of changed file(s)

### ISSUE THREAD

**Issue by themilkman** [p3lim/sublime-toxin#4]
Hi, I really like the way toxin shows the new git status features of ST.

Is it be possible to highlight all parent directories yellow even if the directory is open.

So if the  tree "A > B > C > changed_file" is  unfolded highlight all 3 directories as well as the file.

Maybe another color (or additional italic font?) for directories would be helpful.

I really don't know if this is possible in general or even already in toxin, so any hint appreciated.

Thanks for your work!

**Comment by p3lim** [comment]
Changing that setting requires a restart of ST to take effect.

**Comment by themilkman** [comment]
Wowowowow... that was amazing fast, thank you very much! I'll test it as soon as the package is released on packagecontrol.

**Comment by themilkman** [comment]
Works like a charm, thank you very much @p3lim !
